version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.populate
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-sp3}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-adlibitum}"
      DATABASE_HOST: "${DATABASE_HOST:-db}"
    networks:
      - shared_network


networks:
  shared_network:
    external: true